---

- name: nginx package
  apt:
    name: nginx
    state: present
  become: true

- name: remove default nginx conf
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify:
    - restart nginx

- name: nginx config
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
  become: true
  notify:
    - restart nginx

- name: homeassistant server
  template:
    src: templates/homeassistant
    dest: /etc/nginx/sites-enabled/homeassistant
    owner: pi
    group: pi
  become: true
  notify: restart nginx

- name: add subdomain proxies
  template:
    src: templates/proxy
    dest: "/etc/nginx/sites-enabled/{{ item.subdomain }}"
    owner: pi
    group: pi
  with_items: "{{ proxies }}"
  become: true
  notify: restart nginx

- name: copy any custom sites
  copy:
    src: "{{ nginx_config_dir }}/"
    dest: /etc/nginx/sites-enabled/
    directory_mode: true
    owner: root
    group: root
  become: true
  when: nginx_config_dir is defined
  notify: restart nginx

- name: copy stream configs
  copy:
    src: "{{ nginx_streams_config_dir }}/"
    dest: /etc/nginx/streams/
    directory_mode: true
    owner: root
    group: root
  become: true
  when: nginx_streams_config_dir is defined
  notify: restart nginx

- name: nginx service
  service:
    name: nginx
    enabled: true
    state: started
  become: true
